apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: pool-replicated
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block-replicated
provisioner: ceph.rook.io/block
parameters:
  blockPool: pool-replicated
  clusterNamespace: rook-ceph
  fstype: xfs
reclaimPolicy: Retain