apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: pool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
provisioner: ceph.rook.io/block
parameters:
  blockPool: pool
  clusterNamespace: rook-ceph
  fstype: xfs
reclaimPolicy: Retain