apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: "itzg/minecraft-server:latest"
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        - name: DIFFICULTY
          value: "normal"
        - name: OPS
          value: "Tapus"
        - name: ICON
          value: "https://static.planetminecraft.com/files/resource_media/screenshot/1505/crafting-table-icon8582441.jpg"
        - name: ALLOW_NETHER
          value: "true"
        - name: GENERATE_STRUCTURES
          value: "true"
        - name: FORCE_GAMEMODE
          value: "true"
        - name: MAX_BUILD_HEIGHT
          value: "256"
        - name: VIEW_DISTANCE
          value: "10"
        - name: MODE
          value: "survival"
        - name: LEVEL_TYPE
          value: "DEFAULT"
        - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
          value: "false"
        - name: MAX_MEMORY
          value: "4G"
        volumeMounts:
          - mountPath: /data
            name: minecraft-data
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-pvc
      nodeSelector:
        minecraft-storage: "true"
