---
kind: Job
apiVersion: batch/v1
metadata:
  name: init-fs
spec:
  template:
    metadata:
      name: init-fs
    spec:
      containers:
      - name: init
        image: eu.gcr.io/aircall-interview/rails:1.0.0
        command: ["rake"]
      restartPolicy: Never