ingress:
  enabled: true
  path: /
  hosts:
    - registry.thuault.com
  tls:
    - secretName: registry.thuault.com-tls
      hosts:
        - 'registry.thuault.com'
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
persistence:
  enabled: true
  deleteEnabled: true
  existingClaim: docker-registry
resources:
  limits:
    cpu: 75m
    memory: 75Mi
