---
kind: Service
apiVersion: v1
metadata:
  name: plex
  namespace: media
spec:
  ports:
  - name: plex
    port: 80
    targetPort: 32400
  selector:
    app: plex
---
kind: Service
apiVersion: v1
metadata:
  name: plex-proxy
  namespace: media
spec:
  type: NodePort
  ports:
  - name: pms
    port: 32400
    targetPort: 32400
  selector:
    app: plex
