apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry
  labels:
    name: docker-registry
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/kube/registry"
