apiVersion: v1
data:
  config.xml: |
    <Config>
      <UrlBase>/radarr</UrlBase>
    </Config>
  init-radarr.sh: |
    #!/bin/bash
    cp -n /init-radarr/config.xml /radarr-config/config.xml
kind: ConfigMap
metadata:
  name: init-radarr-cm
