apiVersion: v1
data:
  config.xml: |
    <Config>
      <UrlBase>/sonarr</UrlBase>
    </Config>
  init-sonarr.sh: |
    #!/bin/bash
    cp -n /init-sonarr/config.xml /sonarr-config/config.xml
kind: ConfigMap
metadata:
  name: init-sonarr-cm
