apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    {{- include "media.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9117
      protocol: TCP
      name: jackett-port
  selector:
    app: jackett
