apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    {{- include "media.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 32400
      protocol: TCP
      name: plex-port
  selector:
    app: plex
---
apiVersion: v1
kind: Service
metadata:
  name: plex-proxy
  labels:
    {{- include "media.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 32400
      nodePort: 32400
      protocol: TCP
      name: plex-port
  selector:
    app: plex
