apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  labels:
    {{- include "media.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.general.plexHost }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{ .Values.general.plexHost | quote }}
      secretName: {{ include "media.fullname" . }}-plex-tls
  rules:
    - host: {{ .Values.general.plexHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 80
