apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "media.fullname" . }}-pvc
  labels:
    {{- include "media.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.general.storage.size }}
  selector:
    matchLabels:
      {{- include "media.selectorLabels" . | nindent 6 }}
