apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    {{- include "media.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 7878
      protocol: TCP
      name: radarr-port
  selector:
    app: radarr
