apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    {{- include "media.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9091
      protocol: TCP
      name: trans-port
  selector:
    app: transmission
