---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kibana
  namespace: logging
  labels:
    k8s-app: kibana
spec:
  replicas: 1
  template:
    metadata:
      name: kibana
      labels:
        k8s-app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:5.6.4
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch-logging:9200

