---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-grafana
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Grafana Dashboard"
spec:
  tls:
  - hosts:
    - grafana.thuault.com
    secretName: grafana-tls
  rules:
  - host: grafana.thuault.com
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
