apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minecraft.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "minecraft.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "minecraft.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "minecraft.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 25565
            name: minecraft
          - containerPort: 8123
            name: dynmap
          env:
          - name: EULA
            value: "TRUE"
          - name: DIFFICULTY
            value: "hard"
          - name: OPS
            value: {{ .Values.game.ops }}
          - name: ICON
            value: {{ .Values.game.icon }}
          - name: ALLOW_NETHER
            value: "true"
          - name: GENERATE_STRUCTURES
            value: "true"
          - name: FORCE_GAMEMODE
            value: "true"
          - name: MAX_BUILD_HEIGHT
            value: {{ .Values.game.maxBuildHeight }}
          - name: VIEW_DISTANCE
            value: {{ .Values.game.viewDistance }}
          - name: MODE
            value: "survival"
          - name: LEVEL_TYPE
            value: "DEFAULT"
          - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
            value: "false"
          - name: INIT_MEMORY
            value: {{ .Values.game.minMemory }}
          - name: MAX_MEMORY
            value: {{ .Values.game.maxMemory }}
          - name: TYPE
            value: "SPIGOT"
          - name: VERSION
            value: {{ .Values.game.version }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          - mountPath: /data
            name: {{ include "minecraft.fullname" . }}-data
      volumes:
        - name: {{ include "minecraft.fullname" . }}-data
          persistentVolumeClaim:
            claimName: {{ include "minecraft.fullname" . }}-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
