{{ if .Values.hosting.mapHostname }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ include "minecraft.fullname" . }}-dynmap
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hosting.mapHostname }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.hosting.mapHostname }}
    secretName: {{ include "minecraft.fullname" . }}-tls
  rules:
  - host: {{ .Values.hosting.mapHostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "minecraft.fullname" . }}-dynmap
          servicePort: 80
{{ end }}
