apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "minecraft.fullname" . }}-pv
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minecraft.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.storage.size }}
  hostPath:
    path: {{ .Values.storage.path }}
